# Generated by Django 5.1.3 on 2024-11-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='Student',
        ),
    ]
